### PR TITLE
fix: increase log level to verbose for request processing

### LINKED ISSUE #423: Make log level configurable
By default the log produced by the listener is quite verbose.

The default should be less verbose and we could expose the log level as an optional env variable that allows the log level to be changed for debugging purposes.

### PR DESCRIPTION
**Pull request by mschoettle**
Make log level configurable via `LOG_LEVEL` env variable.
Also increase the log level for most request logging from `info` to `verbose`.

Log levels: https://www.npmjs.com/package/winston#logging-levels

Fixes #423

### CODE REVIEW

File: listener/logs/logger.js [hunk 1]
```diff
@@ -7,7 +7,10 @@
 const {createLogger, format, transports} = require('winston');
 
 // Choose log level according to environment.
-const LoggerLevel = process.env.NODE_ENV === 'production' ? 'info' : 'debug';
+const defaultLoggerLevel = process.env.NODE_ENV === 'production' ? 'info' : 'debug';
+
+// allow the log level to be specifically set via env variable
+const loggerLevel = process.env.LOG_LEVEL ?? defaultLoggerLevel;
```
Comment (staceybeard) [inline listener/logs/logger.js:13]: Could you please add `LOG_LEVEL` to `.env.sample`? It would also be good to list or link to the possible levels, either there or in this file. https://www.npmjs.com/package/winston#logging-levels

File: listener/logs/logger.js [hunk 2]
```diff
@@ -30,7 +33,7 @@ const WinstonLogger = createLogger({
     // Silent logger when running unit tests.
     silent: process.env.DISABLED_LOGGING === 'true',
     // Set level log level
-    level: LoggerLevel,
+    level: loggerLevel,
     // Set log format output in the log file
     format: format.combine(
         format.timestamp({format: 'YYYY-MM-DD HH:mm:ss'}),
```
Comment (staceybeard) [inline listener/logs/logger.js:39]: I tested with `LOG_LEVEL=error` (and it prints `INFO: Initialized Winston with level: error`), but I still see debug printouts in the console. Maybe because of `new transports.Console({level: 'debug'})`.

Comment (mschoettle) [reply listener/logs/logger.js:39]: Indeed. The log level on the transport takes precedence. We could remove those which then uses the global log level.

Or, for file logging we could do `warning` or `error`.

File: listener/logs/logger.js (hunk 1 above)
Comment (mschoettle) [reply listener/logs/logger.js:13]: I didn't put it in there because `DISABLE_LOGGING` wasn't defined either. I put both into the sample file and left them commented out.

File: listener/logs/logger.js (hunk 2 above)
Comment (mschoettle) [reply listener/logs/logger.js:39]: Removed the separate log level and changed file logging to error.

In the deployment we should expose the logs to the host so that we do not lose them.

File: listener/logs/logger.js (hunk 1 above)
Comment (staceybeard) [reply listener/logs/logger.js:13]: Thanks, looks great!

**Review by staceybeard — APPROVED** [review]
